<?php

/**
 * @file
 * Contains functions for the commerce_pos_manufacturer_coupon module
 */

/**
 * Implements hook_commerce_pos_action_info().
 */
function commerce_pos_manufacturer_coupon_commerce_pos_action_info() {
  //Define an action to add deposits and refunds thereof.
  return array(
    'commerce_pos_manufacturer_coupon_upc' => array(
      'weight' => 80,
      'action text' => 'MC',
      'callbacks' => array(
        'parse' => 'commerce_pos_manufacturer_coupon_upc_parse',
        'validate' => array('commerce_pos_order_require_modifiable_order', 'commerce_pos_manufacturer_coupon_upc_validate'),
        'execute' => array('commerce_pos_manufacturer_coupon_upc_execute'),
        'extract' => array('commerce_pos_manufacturer_coupon_upc_extract'),
      ),
    ),
  );
}

/**
 * Parse callback for UPC manufacturer coupon action.
 */
function commerce_pos_manufacturer_coupon_upc_parse($input, $action_text = 'MC') {
  //TODO: add in a check on the UPC checksum
  return is_numeric($input) && drupal_strlen($input) == 12 && $input[0] == '5';
}

/**
 * Extract callback for the deposit action.
 */
function commerce_pos_manufacturer_coupon_upc_extract(&$variables, $values) {
  $variables['coupon_upc'] = $values['input'];
}

/**
 * Validate callback for the deposit action.
 */
function commerce_pos_manufacturer_coupon_upc_validate(&$variables) {
  //Determine whether this order qualifies for this coupon.
  $order = $variables['order'];
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $coupon_upc = $variables['coupon_upc'];
  $value_code = drupal_substr($coupon_upc, 9, 2);
  $value = commerce_pos_manufacturer_coupon_value_lookup($value_code);
  $man_fam = drupal_substr($coupon_upc, 1, 8);
watchdog('value', print_r($value, 1));
  $eligible_line_items = array();
  $coupon_line_items = array();

  //Collect all the line items which this coupon can apply to and other coupon line items.
  foreach ($order_wrapper->commerce_line_items as $line_item_wrapper) {
    if (commerce_pos_manufacturer_coupon_line_item_match($coupon_upc, $line_item_wrapper->value())) {
      $amount = $line_item_wrapper->commerce_unit_price->amount->value();
      $currency_code = $line_item_wrapper->commerce_unit_price->currency_code->value();
      $eligible_line_items[$line_item_wrapper->line_item_id->value()] = array(
        'quantity' => $line_item_wrapper->quantity->value(),
        'unit_price:amount' => commerce_currency_convert($amount, $currency_code, 'USD'),
        'line_item_id' => $line_item_wrapper->line_item_id->value(),
      );
    }
  }

  //Determine which ones already have coupons applied.
  foreach ($order_wrapper->commerce_line_items as $line_item_wrapper) {
    if ($line_item_wrapper->type->value() == 'manufacturer_coupon') {
      $target_products = commerce_pos_manufacturer_coupon_applied_to($line_item_wrapper->value());
      foreach ($target_products as $line_item_id => $data) {
        $eligible_line_items[$line_item_id]['quantity'] -= $data['quantity'];
      }
    }
  }

  //Check whether the order has enough qualifying items to apply the coupon.
  $eligible_quantity = 0;
  foreach($eligible_line_items as $line_item_id => $data) {
    $eligible_quantity += $data['quantity'];
  }
  //If so, apply the coupon.
  if ($eligible_quantity >= $value['quantity']) {
    //Sort eligible items by price.
    usort($eligible_line_items, '_commerce_pos_manufacturer_coupon_price_compare');
    //Reverse the array if it's a free coupon so that we apply to most expensive items.
    if ($value['type'] == 'free') {
      $eligible_line_items = array_reverse($eligible_line_items);
    }
    //Apply the coupon to the requisite number of the product.
    $quantity_applied = 0;
    $applied_to = array();
    foreach ($eligible_line_items as $product_data) {
      $line_item = commerce_line_item_load($product_data['line_item_id']);
      //Determine the quantity on this line item.
      $quantity = intval(min($line_item->quantity, $value['quantity'] - $quantity_applied));
      $info = array(
        'quantity' => $quantity,
      );
      if ($value['type'] == 'flat') {
        $info['amount'] = $quantity * $amount / $value['quantity'];
      }
      $applied_to[$line_item->line_item_id] = $info;
      $quantity_applied += $quantity;
      if (intval($quantity_applied) == $value['quantity'] ) {
        if ($value['type'] == 'flat') {
          $amount = $value['amount'];
        }
        elseif ($value['type'] == 'free') {
          $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
          $amount = $line_item_wrapper->commerce_unit_price->amount->value();
          $data['free_line_item_id'] = $line_item->line_item_id;
        }
        $applied_to[$line_item->line_item_id]['amount'] = $amount;
        break;
      }
    }

    $variables['data'] = array(
    	'type' => 'upc',
      'coupon_upc' => $coupon_upc,
      'applied_to' => $applied_to,
    );

    $variables['value']['amount'] = $applied_to[$line_item->line_item_id]['amount'];
    watchdog('test', print_r($variables, 1));
  }
  else {
    return array(t('Insufficient quantity purchased.'));
  }
}

/**
 * Determine which line items a coupon has been applied to.
 */
function commerce_pos_manufacturer_coupon_applied_to($line_item) {
  return $line_item->data['applied_to'];
}

/**
 * Comparison callback for sorting eligible line item data by price.
 */
function _commerce_pos_manufacturer_coupon_price_compare($a, $b) {
  return intval($a['unit_price:amount'] - $b['unit_price:amount']);
}

/**
 * Determines whether a given line item is eligible for a coupon.
 */
function commerce_pos_manufacturer_coupon_line_item_match($coupon_upc, $line_item) {
  $man_fam = drupal_substr($coupon_upc, 1, 8);

  if ($line_item->type == 'product') {
    $wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
    $sku = $wrapper->commerce_product->sku->value();
    return drupal_substr($sku, 1, 8) == $man_fam || (drupal_substr($sku, 1, 5) == drupal_substr($man_fam, 0, 5) && $man_fam[7] == '0');
  }
  return FALSE;
}

/**
 * Returns the UPC Coupon code data.
 *
 * @param $code
 *  A two-digit UPC coupon code.
 *
 * @return
 * 	An array corresponding to the coupon code given by $code, keyed by
 * 	'type' (either 'flat' or 'free') and 'quantity' (as in quantity required)
 * 	and 'amount' (as an integer) if the type is 'flat'
 */
function commerce_pos_manufacturer_coupon_value_lookup($code) {
  $codes = array(
    '01' => array('type' => 'free', 'quantity' => 1),
    //Note that quantity includes the free one!
    '02' => array('type' => 'free', 'quantity' => 5),
    '03' => array('type' => 'flat', 'amount' => 110),
    '04' => array('type' => 'flat', 'amount' => 135),
    '05' => array('type' => 'flat', 'amount' => 140),
    '06' => array('type' => 'flat', 'amount' => 160),
    '07' => array('type' => 'flat', 'amount' => 150, 'quantity' => 3),
    '08' => array('type' => 'flat', 'amount' => 300, 'quantity' => 2),
  	'09' => array('type' => 'flat', 'amount' => 200, 'quantity' => 3),
  	'10' => array('type' => 'flat', 'amount' => 10),
    '11' => array('type' => 'flat', 'amount' => 185),
  	'12' => array('type' => 'flat', 'amount' => 12),
    '13' => array('type' => 'flat', 'amount' => 100, 'quantity' => 4),
    '14' => array('type' => 'free', 'quantity' => 2),
    '15' => array('type' => 'flat', 'amount' => 15),
    '16' => array('type' => 'free', 'quantity' => 3),
    //17 is reserved for future use.
  	'17' => array(),
    '18' => array('type' => 'flat', 'amount' => 260),
    '19' => array('type' => 'free', 'quantity' => 4),
    '20' => array('type' => 'flat', 'amount' => 20),
    '21' => array('type' => 'flat', 'quantity' => 2, 'amount' => 35),
    '22' => array('type' => 'flat', 'quantity' => 2, 'amount' => 40),
    '23' => array('type' => 'flat', 'quantity' => 2, 'amount' => 45),
    '24' => array('type' => 'flat', 'quantity' => 2, 'amount' => 50),
    '25' => array('type' => 'flat', 'amount' => 25),
    '26' => array('type' => 'flat', 'amount' => 285),
    '27' => array(),
    '28' => array('type' => 'flat', 'quantity' => 2, 'amount' => 55),
    '29' => array('type' => 'flat', 'amount' => 29),
    '30' => array('type' => 'flat', 'amount' => 30),
    '31' => array('type' => 'flat', 'quantity' => 2, 'amount' => 60),
    '32' => array('type' => 'flat', 'quantity' => 2, 'amount' => 75),
    '33' => array('type' => 'flat', 'quantity' => 2, 'amount' => 100),
    '34' => array('type' => 'flat', 'quantity' => 2, 'amount' => 125),
    '35' => array('type' => 'flat', 'amount' => 35),
    '36' => array('type' => 'flat', 'quantity' => 2, 'amount' => 150),
    '37' => array('type' => 'flat', 'quantity' => 3, 'amount' => 25),
    '38' => array('type' => 'flat', 'quantity' => 3, 'amount' => 30),
    '39' => array('type' => 'flat', 'amount' => 39),
    '40' => array('type' => 'flat', 'amount' => 40),
    '41' => array('type' => 'flat', 'quantity' => 3, 'amount' => 50),
    '42' => array('type' => 'flat', 'quantity' => 3, 'amount' => 100),
    '43' => array('type' => 'flat', 'quantity' => 2, 'amount' => 110),
    '44' => array('type' => 'flat', 'quantity' => 2, 'amount' => 135),
    '45' => array('type' => 'flat', 'amount' => 45),
    '46' => array('type' => 'flat', 'quantity' => 2, 'amount' => 160),
    '47' => array('type' => 'flat', 'quantity' => 2, 'amount' => 175),
    '48' => array('type' => 'flat', 'quantity' => 2, 'amount' => 185),
    '49' => array('type' => 'flat', 'amount' => 49),
    '50' => array('type' => 'flat', 'amount' => 50),
    '51' => array('type' => 'flat', 'quantity' => 2, 'amount' => 200),
    '52' => array('type' => 'flat', 'quantity' => 3, 'amount' => 55),
    '53' => array('type' => 'flat', 'quantity' => 2, 'amount' => 10),
    '54' => array('type' => 'flat', 'quantity' => 2, 'amount' => 15),
    '55' => array('type' => 'flat', 'amount' => 55),
    '56' => array('type' => 'flat', 'quantity' => 2, 'amount' => 20),
    '57' => array('type' => 'flat', 'quantity' => 2, 'amount' => 25),
    '58' => array('type' => 'flat', 'quantity' => 2, 'amount' => 30),
    '59' => array('type' => 'flat', 'amount' => 59),
    '60' => array('type' => 'flat', 'amount' => 60),
    '61' => array('type' => 'flat', 'amount' => 61),
    '62' => array('type' => 'flat', 'amount' => 950),
    '63' => array('type' => 'flat', 'amount' => 900),
    '64' => array('type' => 'flat', 'amount' => 850),
    '65' => array('type' => 'flat', 'amount' => 65),
    '66' => array('type' => 'flat', 'amount' => 800),
    '67' => array('type' => 'flat', 'amount' => 750),
    '68' => array('type' => 'flat', 'amount' => 700),
    '69' => array('type' => 'flat', 'amount' => 69),
    '70' => array('type' => 'flat', 'amount' => 70),
    '71' => array('type' => 'flat', 'amount' => 650),
    '72' => array('type' => 'flat', 'amount' => 600),
    '73' => array('type' => 'flat', 'amount' => 550),
    '74' => array('type' => 'flat', 'amount' => 500),
    '75' => array('type' => 'flat', 'amount' => 75),
    '76' => array('type' => 'flat', 'amount' => 100),
    '77' => array('type' => 'flat', 'amount' => 125),
    '78' => array('type' => 'flat', 'amount' => 150),
    '79' => array('type' => 'flat', 'amount' => 79),
    '80' => array('type' => 'flat', 'amount' => 80),
    '81' => array('type' => 'flat', 'amount' => 175),
    '82' => array('type' => 'flat', 'amount' => 200),
    '83' => array('type' => 'flat', 'amount' => 225),
    '84' => array('type' => 'flat', 'amount' => 250),
    '85' => array('type' => 'flat', 'amount' => 85),
    '86' => array('type' => 'flat', 'amount' => 275),
    '87' => array('type' => 'flat', 'amount' => 300),
    '88' => array('type' => 'flat', 'amount' => 325),
    '89' => array('type' => 'flat', 'amount' => 89),
    '90' => array('type' => 'flat', 'amount' => 90),
    '91' => array('type' => 'flat', 'amount' => 350),
    '92' => array('type' => 'flat', 'amount' => 375),
    '93' => array('type' => 'flat', 'amount' => 400),
    '94' => array(),
    '95' => array('type' => 'flat', 'amount' => 95),
    '96' => array('type' => 'flat', 'amount' => 450),
    '97' => array(),
    '98' => array('type' => 'flat', 'quantity' => 2, 'amount' => 65),
    '99' => array('type' => 'flat', 'amount' => 99),
    '00' => array(),
  );

  $return = $codes[$code];
  $return += array('quantity' => 1);
  return $return;
}

/**
 * Execute callback for the deposit action.
 */
function commerce_pos_manufacturer_coupon_upc_execute(&$variables) {
  $data = $variables['data'];
  $order = $variables['order'];
  $quantity = 1;
  $coupon_upc = $variables['coupon_upc'];

  //As far as I can tell, the UPC coupon specifically encodes USD amounts only
  $price = array(
    'currency_code' => 'USD',
    'amount' => -$variables['value']['amount'],
  );

  $line_item = commerce_pos_manufacturer_coupon_line_item_new($coupon_upc, $order, 1, $price);
  //To speed up insertion, we save coupon data in the serialized data
  //field, rather than creating fields for the data.
  $line_item->data = $data;

  $line_item->line_item_label = t('Manufacturer coupon');

  commerce_pos_line_item_add_to_order($line_item, $order);
  commerce_order_save($order);
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
function commerce_pos_manufacturer_coupon_commerce_line_item_type_info() {
  return array(
    'manufacturer_coupon' => array(
      'type' => 'manufacturer_coupon',
      'name' => t('Manufacturer\'s coupon'),
      'description' => t('A discount from a manufacturer\'s coupon.'),
      'add_form_submit_value' => t('Add coupons'),
      'base' => 'commerce_pos_manufacturer_coupon_line_item',
    ),
  );
}

/**
 * Returns an appropriate title for this line item.
 */
function commerce_pos_manufacturer_coupon_line_item_title($line_item) {
  return t('Manufacturer\'s coupon');
}

/**
 * Creates a new deposit line item populated with the proper deposit values.
 *
 * @param $deposit
 *   The fully loaded deposit referenced by the line item.
 * @param $quantity
 *   The quantity to set for the deposit.
 * @param $order_id
 *   The ID of the order the line item belongs to (if available).
 * @param $display_uri
 *   A URI array as returned by entity_uri() indicating the display to link the
 *     deposit line item to; defaults to NULL for no display.
 *
 * @return
 *   The fully loaded line item populated with the deposit data as specified.
 */
function commerce_pos_manufacturer_coupon_line_item_new($coupon_upc, $order = NULL, $quantity = 1, $price = array(), $display_uri = NULL) {
  // Create the new line item.
  $order_id = empty($order) ? NULL : $order->order_id;

  $line_item = entity_create('commerce_line_item', array(
    'type' => 'manufacturer_coupon',
    'order_id' => $order_id,
    'quantity' => $quantity,
  ));

  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

  $price += array(
    'amount' => 0,
    'currency_code' => commerce_pos_default_currency(),
  );

  $price+= array('data' => array());

  // Add the base price to the components array.
  if (!commerce_price_component_load($price, 'base_price')) {
    $price['data'] = commerce_price_component_add(
      $price,
      'base_price',
      $price,
      TRUE
    );
  }

  $line_item_wrapper->commerce_unit_price = $price;

  // Return the line item.
  return $line_item;
}

/**
 * Implements hook_commerce_pos_snap_eligible_components().
 */
function commerce_pos_manufacturer_coupon_commerce_pos_snap_eligible_components($line_item) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $line_item->order_id);
  foreach ($order_wrapper->commerce_line_items as $line_item_wrapper) {
    if ($line_item_wrapper->type->value() == 'manufacturer_coupon') {
      $coupon_line_item = $line_item_wrapper->value();
      $applied_to = commerce_pos_manufacturer_coupon_applied_to($coupon_line_item);
      if (isset($applied_to[$line_item->line_item_id]) &&
        is_array($applied_to[$line_item->line_item_id])) {
        return array(
          array(
          	'currency_code' => $line_item_wrapper->commerce_total->currency_code->value(),
          	'amount' => - $applied_to[$line_item->line_item_id]['quantity'] * $applied_to[$line_item->line_item_id]['amount'],
          ),
        );
      }
    }
  }
}
